server:
    port: 8080
    app:
        ad-domain: com.example
        ad-server: ldap://com.example/
        service-principal: HTTP/testInventory@example.com
        keytab-location: /tmp/tomcat.keytab
        ldap-search-base: dc=example,dc=com
        ldap-search-filter: "(| (userPrincipalName={0}) (sAMAccountName={0}))"
